Resources:
  RDSDBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: '100'
      AutomaticBackupReplicationRegion: ap-northeast-1
      BackupRetentionPeriod: 1
      DBInstanceClass: db.t3.micro
      Engine: postgres
      Iops: 1000
      MasterUserPassword: masterpassword
      MasterUsername: masteruser
      StorageType: IO1
